// Isolated candidate63 qualification. Preserved57 fixture and61 raster shaders
// are reused without edits. AMD AddrLib supplies every golden address.
#define main Retained57Main
#include "gpu_color_sample_tiling_probe.cpp"
#undef main
#include "prx/libSceAgcDriver/Graphics/shaders/ColorSampleTiling_spv.h"
#include "ColorSnapshotRaster_spv.h"
#include <bit>
#include <map>
#include <set>
#include <string>
#include <numeric>

namespace pixel_probe {
using Tiler = AgcDriver::Graphics::GpuColorSampleTiler;
using AgcDriver::Graphics::ColorTarget;
using AgcDriver::Graphics::ColorTileMode;
unsigned ownerIdentity=0;
bool ownerPixel=false, fenceComplete=true, injectDuplicateZ=false;
enum class Mutation { None, WrongXor, MissingPlane };
Mutation mutation=Mutation::None;
struct Module { bool original; std::size_t bytes; std::uint64_t fingerprint; unsigned owner; };
struct Program { unsigned owner,samples,direction,schema,slot; bool pixel; VkShaderModule module; };
std::map<VkShaderModule,Module> modules;
std::map<VkPipeline,Program> programs;
std::map<unsigned,std::set<unsigned>> slots;
std::set<VkDescriptorPool> pendingPools;
Program* bound=nullptr;
unsigned legacyDispatches=0,pixelDispatches=0,duplicateRejected=0,negativePrograms=0;
std::uint64_t descriptorFenceChecks=0;
VKAPI_ATTR VkResult VKAPI_CALL module(VkDevice d,const VkShaderModuleCreateInfo* info,const VkAllocationCallbacks* a,VkShaderModule* out){
 auto result=vkCreateShaderModule(d,info,a,out);if(result==VK_SUCCESS){std::uint64_t digest=1469598103934665603ull;for(std::size_t i=0;i<info->codeSize/4;++i){digest^=info->pCode[i];digest*=1099511628211ull;}modules[*out]={info->codeSize==sizeof(COLOR_SAMPLE_TILING_COMP_SPV)&&std::memcmp(info->pCode,COLOR_SAMPLE_TILING_COMP_SPV,info->codeSize)==0,info->codeSize,digest,ownerIdentity};}return result;
}
VKAPI_ATTR VkResult VKAPI_CALL pipelines(VkDevice d,VkPipelineCache cache,unsigned count,const VkComputePipelineCreateInfo* input,const VkAllocationCallbacks* a,VkPipeline* out){
 require(count==1,"fixture expects one compute pipeline creation");auto info=*input;std::array<std::uint32_t,23> values{};VkSpecializationInfo specialization{};Program record{};bool tiling=false;
 if(info.stage.pSpecializationInfo){const auto& spec=*info.stage.pSpecializationInfo;if(spec.mapEntryCount==20||spec.mapEntryCount==23){tiling=true;require(spec.dataSize==spec.mapEntryCount*4,"specialization byte schema");for(unsigned i=0;i<spec.mapEntryCount;++i){require(spec.pMapEntries[i].constantID==i&&spec.pMapEntries[i].offset==i*4&&spec.pMapEntries[i].size==4,"specialization map identity");std::memcpy(&values[i],static_cast<const std::byte*>(spec.pData)+i*4,4);}const auto* eq=AgcDriver::Graphics::FindColorSampleSwizzleEquation(4,values[0]);require(eq&&values[1]<2&&values[2]==eq->blockWidth&&values[3]==eq->blockHeight,"program layout identity");for(unsigned i=0;i<16;++i)require(values[i+4]==eq->bits[i],"original AMD equation schema changed");const bool pixel=spec.mapEntryCount==23;require(pixel==(ownerPixel&&values[0]==8),"captured owner gate changed pipeline schema");require(modules.contains(info.stage.module),"unknown compute module");require(modules.at(info.stage.module).original!=pixel,"pixel/legacy shader module identity");require(modules.at(info.stage.module).owner==ownerIdentity,"module crossed owner cache");if(pixel){require(values[20]==0x4000&&values[21]==0x8000&&values[22]==0x0800,"sample-plane byte XOR specializations");if(mutation==Mutation::WrongXor){values[20]^=0x0100;++negativePrograms;}if(mutation==Mutation::MissingPlane){values[22]=0;++negativePrograms;}}
 record={ownerIdentity,values[0],values[1],spec.mapEntryCount,pixel?6u+values[1]:(unsigned(std::countr_zero(values[0]))-1)*2+values[1],pixel,info.stage.module};specialization=spec;specialization.pData=values.data();info.stage.pSpecializationInfo=&specialization;}}
 auto result=vkCreateComputePipelines(d,cache,count,&info,a,out);if(result==VK_SUCCESS){++pipelineCreations;if(tiling){require(!slots[ownerIdentity].contains(record.slot),"immutable program rebuilt instead of cache reuse");slots[ownerIdentity].insert(record.slot);programs[*out]=record;std::printf("[pixel-program] owner=%u samples=%u direction=%u schema=%u cache_slot=%u original_module=%u shader_bytes=%zu module_fingerprint=%016llx mutation=%u\n",record.owner,record.samples,record.direction,record.schema,record.slot,unsigned(!record.pixel),modules.at(record.module).bytes,(unsigned long long)modules.at(record.module).fingerprint,unsigned(mutation));}}return result;
}
VKAPI_ATTR void VKAPI_CALL bind(VkCommandBuffer c,VkPipelineBindPoint point,VkPipeline p){if(point==VK_PIPELINE_BIND_POINT_COMPUTE){auto it=programs.find(p);bound=it==programs.end()?nullptr:&it->second;}vkCmdBindPipeline(c,point,p);}
VKAPI_ATTR void VKAPI_CALL launch(VkCommandBuffer c,unsigned x,unsigned y,unsigned z){if(bound){const unsigned expected=bound->pixel?1:bound->samples;require(bound->owner==ownerIdentity,"bound program owner identity");const unsigned attempted=injectDuplicateZ&&bound->pixel?8:z;if(attempted!=expected){++duplicateRejected;fenceComplete=true;throw std::runtime_error("host dispatch contract rejected duplicate Z8");}require(z==expected,"production dispatch-Z contract");if(bound->pixel)++pixelDispatches;else ++legacyDispatches;}vkCmdDispatch(c,x,y,z);}
VKAPI_ATTR VkResult VKAPI_CALL pool(VkDevice d,const VkDescriptorPoolCreateInfo* info,const VkAllocationCallbacks* a,VkDescriptorPool* out){auto result=trackedPool(d,info,a,out);if(result==VK_SUCCESS)pendingPools.insert(*out);return result;}
VKAPI_ATTR void VKAPI_CALL destroyPool(VkDevice d,VkDescriptorPool p,const VkAllocationCallbacks* a){require(fenceComplete,"descriptors destroyed before GPU fence");pendingPools.erase(p);trackedDestroyPool(d,p,a);}
VKAPI_ATTR PFN_vkVoidFunction VKAPI_CALL resolve(VkDevice d,const char* name){
 if(std::strcmp(name,"vkCreateShaderModule")==0)return reinterpret_cast<PFN_vkVoidFunction>(module);
 if(std::strcmp(name,"vkCreateComputePipelines")==0)return reinterpret_cast<PFN_vkVoidFunction>(pipelines);
 if(std::strcmp(name,"vkCmdBindPipeline")==0)return reinterpret_cast<PFN_vkVoidFunction>(bind);
 if(std::strcmp(name,"vkCmdDispatch")==0)return reinterpret_cast<PFN_vkVoidFunction>(launch);
 if(std::strcmp(name,"vkCreateDescriptorPool")==0)return reinterpret_cast<PFN_vkVoidFunction>(pool);
 if(std::strcmp(name,"vkDestroyDescriptorPool")==0)return reinterpret_cast<PFN_vkVoidFunction>(destroyPool);
 return vkGetDeviceProcAddr(d,name);
}
struct Owner {unsigned id;bool pixel;std::unique_ptr<Tiler> tiler;Owner(Device& d,unsigned id,bool pixel,const char* gate):id(id),pixel(pixel){setenv("APS5_GPU_COLOR_SAMPLE_PIXEL_OWNED",gate,1);activate();tiler=std::make_unique<Tiler>(d.context);}void activate(){ownerIdentity=id;ownerPixel=pixel;}};
struct Golden {VkExtent2D extent;unsigned samples;Push push;std::vector<std::uint64_t> offsets;std::vector<bool> logical;std::vector<std::byte> linear,tiled;};
Golden golden(Oracle& oracle,VkExtent2D extent,unsigned samples){
 ADDR2_COMPUTE_SURFACE_INFO_INPUT info{};info.size=sizeof(info);info.flags.color=1;info.swizzleMode=ADDR_SW_64KB_R_X;info.resourceType=ADDR_RSRC_TEX_2D;info.bpp=32;info.width=extent.width;info.height=extent.height;info.numSlices=info.numMipLevels=1;info.numSamples=info.numFrags=samples;
 ADDR2_COMPUTE_SURFACE_INFO_OUTPUT geometry{};geometry.size=sizeof(geometry);require(Addr2ComputeSurfaceInfo(oracle.library,&info,&geometry)==ADDR_OK,"AMD geometry");const auto* eq=AgcDriver::Graphics::FindColorSampleSwizzleEquation(4,samples);require(eq&&geometry.blockWidth==eq->blockWidth&&geometry.blockHeight==eq->blockHeight&&geometry.baseAlign==65536,"AMD block geometry");
 Golden g{extent,samples,{extent.width,extent.height,geometry.pitch/geometry.blockWidth,unsigned(geometry.surfSize/4),extent.width*extent.height*samples}};g.offsets.resize(g.push.linearWords);g.logical.resize(g.push.tiledWords);g.linear.resize(std::size_t(g.push.linearWords)*4);g.tiled.assign(geometry.surfSize,std::byte{0xa5});
 ADDR2_COMPUTE_SURFACE_ADDRFROMCOORD_INPUT coord{};coord.size=sizeof(coord);coord.flags=info.flags;coord.swizzleMode=info.swizzleMode;coord.resourceType=info.resourceType;coord.bpp=32;coord.unalignedWidth=extent.width;coord.unalignedHeight=extent.height;coord.numSlices=coord.numMipLevels=1;coord.numSamples=coord.numFrags=samples;
 for(unsigned y=0;y<extent.height;++y)for(unsigned x=0;x<extent.width;++x)for(unsigned s=0;s<samples;++s){coord.x=x;coord.y=y;coord.sample=s;ADDR2_COMPUTE_SURFACE_ADDRFROMCOORD_OUTPUT out{};out.size=sizeof(out);require(Addr2ComputeSurfaceAddrFromCoord(oracle.library,&coord,&out)==ADDR_OK,"AMD coordinate");require(out.bitPosition==0&&out.addr%4==0&&out.addr+4<=g.tiled.size()&&!g.logical[out.addr/4],"AMD offset range/bijection");g.logical[out.addr/4]=true;const auto i=(std::size_t(y)*extent.width+x)*samples+s;g.offsets[i]=out.addr;const auto value=pattern(x,y,s);std::memcpy(g.linear.data()+4*i,&value,4);std::memcpy(g.tiled.data()+out.addr,&value,4);}return g;
}
ColorTarget target(const Golden& g){ColorTarget color{};color.address=0x10000;color.extent=g.extent;color.format=VK_FORMAT_R8G8B8A8_UNORM;color.bytes=g.tiled.size();color.tileMode=ColorTileMode::RenderTarget;color.samples=color.fragments=g.samples;return color;}
void record(Device& d,Owner& owner,const Golden& g,bool retile,const ::Buffer& src,const ::Buffer& dst,VkPipelineStageFlags srcStage=VK_PIPELINE_STAGE_HOST_BIT,VkAccessFlags srcAccess=VK_ACCESS_HOST_WRITE_BIT,VkPipelineStageFlags dstStage=VK_PIPELINE_STAGE_HOST_BIT,VkAccessFlags dstAccess=VK_ACCESS_HOST_WRITE_BIT){owner.activate();auto color=target(g);require(Tiler::Supports(d.context,color),"qualified AMD layout rejected");auto transfer=std::make_unique<Tiler::Transfer>(*owner.tiler,color);transfer->Record(d.commands,retile,{d.device,src.buffer,src.offset,src.bytes,srcStage,srcAccess},{d.device,dst.buffer,dst.offset,dst.bytes,dstStage,dstAccess},VK_PIPELINE_STAGE_HOST_BIT,VK_ACCESS_HOST_READ_BIT);d.retained.push_back(std::move(transfer));}
void begin(Device& d){require(fenceComplete,"previous fence incomplete");d.begin();fenceComplete=false;bound=nullptr;}
void submit(Device& d){const auto outstanding=pendingPools.size();require(outstanding>0,"no retained tiling descriptors");d.submit();require(pendingPools.size()==outstanding,"descriptors released during fence wait");descriptorFenceChecks+=outstanding;fenceComplete=true;d.retained.clear();}
std::vector<std::byte> expectedRetile(const Golden& g,unsigned seed,bool changed){std::vector<std::byte> result(g.tiled.size(),std::byte(seed));for(std::size_t i=0;i<g.offsets.size();++i){std::uint32_t value;std::memcpy(&value,g.linear.data()+4*i,4);if(changed)value^=0x58fb2973u;std::memcpy(result.data()+g.offsets[i],&value,4);}return result;}
std::vector<std::byte> compute(Device& d,Owner& owner,const Golden& g,unsigned mode,VkQueryPool query=VK_NULL_HANDLE){
 ::Buffer tiled(d,g.tiled.size()),linear(d,g.linear.size()),retiled(d,g.tiled.size());std::memcpy(tiled.data(),g.tiled.data(),g.tiled.size());std::memset(linear.data(),0xca,g.linear.size());std::memset(retiled.data(),0x5a,g.tiled.size());
 if(mode==1){std::memcpy(linear.data(),g.linear.data(),g.linear.size());for(std::size_t i=0;i<g.linear.size();i+=4){std::uint32_t word;std::memcpy(&word,linear.data()+i,4);word^=0x58fb2973u;std::memcpy(linear.data()+i,&word,4);}}
 begin(d);if(query){vkCmdResetQueryPool(d.commands,query,0,2);vkCmdWriteTimestamp(d.commands,VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,query,0);}
 if(mode==0)record(d,owner,g,false,tiled,linear);else if(mode==1)record(d,owner,g,true,linear,retiled);else{record(d,owner,g,false,tiled,linear);barrier(d,tiled,VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,VK_ACCESS_SHADER_READ_BIT,VK_PIPELINE_STAGE_TRANSFER_BIT,VK_ACCESS_TRANSFER_WRITE_BIT);vkCmdFillBuffer(d.commands,tiled.buffer,tiled.offset,tiled.bytes,0xfefefefeu);record(d,owner,g,true,linear,tiled,VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,VK_ACCESS_SHADER_WRITE_BIT,VK_PIPELINE_STAGE_TRANSFER_BIT,VK_ACCESS_TRANSFER_WRITE_BIT);barrier(d,linear,VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,VK_ACCESS_SHADER_READ_BIT,VK_PIPELINE_STAGE_HOST_BIT,VK_ACCESS_HOST_READ_BIT);}
 if(query)vkCmdWriteTimestamp(d.commands,VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT,query,1);submit(d);require(tiled.guardErrors()+linear.guardErrors()+retiled.guardErrors()==0,"nonzero-offset buffer guard corruption");
 if(mode!=2)require(compareBytes(tiled.data(),g.tiled)==0,"compute mutated tiled source");if(mode==0)return{linear.data(),linear.data()+g.linear.size()};if(mode==1)return{retiled.data(),retiled.data()+g.tiled.size()};require(compareBytes(linear.data(),g.linear)==0,"poison chain linear mismatch");return{tiled.data(),tiled.data()+g.tiled.size()};
}
struct Raster {
 Device& d;AgcDriver::Graphics::RenderTarget& target;VkRenderPass pass{};VkPipelineLayout layout{};VkPipeline pipeline{};std::vector<VkFramebuffer> framebuffers;
 Raster(Device& d,AgcDriver::Graphics::RenderTarget& t):d(d),target(t){VkShaderModule vs{},fs{};try{
  VkAttachmentDescription attachment{};attachment.format=t.Format();attachment.samples=t.NativeSamples();attachment.loadOp=VK_ATTACHMENT_LOAD_OP_LOAD;attachment.storeOp=VK_ATTACHMENT_STORE_OP_STORE;attachment.initialLayout=attachment.finalLayout=VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
  const VkAttachmentReference ref{0,VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL};VkSubpassDescription sub{};sub.pipelineBindPoint=VK_PIPELINE_BIND_POINT_GRAPHICS;sub.colorAttachmentCount=1;sub.pColorAttachments=&ref;VkRenderPassCreateInfo pi{VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO};pi.attachmentCount=1;pi.pAttachments=&attachment;pi.subpassCount=1;pi.pSubpasses=&sub;check(vkCreateRenderPass(d.device,&pi,nullptr,&pass),"raster renderpass");
  for(unsigned g=0;g<t.Groups();++g){auto view=t.View(g);VkFramebufferCreateInfo fi{VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO};fi.renderPass=pass;fi.attachmentCount=1;fi.pAttachments=&view;fi.width=t.Extent().width;fi.height=t.Extent().height;fi.layers=1;VkFramebuffer fb{};check(vkCreateFramebuffer(d.device,&fi,nullptr,&fb),"raster framebuffer");framebuffers.push_back(fb);}
  const VkPushConstantRange push{VK_SHADER_STAGE_VERTEX_BIT|VK_SHADER_STAGE_FRAGMENT_BIT,0,16};VkPipelineLayoutCreateInfo li{VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO};li.pushConstantRangeCount=1;li.pPushConstantRanges=&push;check(vkCreatePipelineLayout(d.device,&li,nullptr,&layout),"raster layout");
  const auto module=[&](const auto& words,VkShaderModule& output){VkShaderModuleCreateInfo mi{VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO};mi.codeSize=sizeof(words);mi.pCode=words;check(vkCreateShaderModule(d.device,&mi,nullptr,&output),"raster shader");};module(COLOR_SNAPSHOT_RASTER_VERT_SPV,vs);module(COLOR_SNAPSHOT_RASTER_FRAG_SPV,fs);
  const std::array<VkPipelineShaderStageCreateInfo,2> stages{{{VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,nullptr,0,VK_SHADER_STAGE_VERTEX_BIT,vs,"main",nullptr},{VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,nullptr,0,VK_SHADER_STAGE_FRAGMENT_BIT,fs,"main",nullptr}}};
  VkPipelineVertexInputStateCreateInfo vi{VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO};VkPipelineInputAssemblyStateCreateInfo ia{VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO};ia.topology=VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST;
  VkPipelineViewportStateCreateInfo vp{VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO};vp.viewportCount=vp.scissorCount=1;VkPipelineRasterizationStateCreateInfo rs{VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO};rs.polygonMode=VK_POLYGON_MODE_FILL;rs.cullMode=VK_CULL_MODE_NONE;rs.lineWidth=1;
  VkPipelineMultisampleStateCreateInfo ms{VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO};ms.rasterizationSamples=t.NativeSamples();VkPipelineColorBlendAttachmentState ba{};ba.colorWriteMask=15;VkPipelineColorBlendStateCreateInfo bs{VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO};bs.attachmentCount=1;bs.pAttachments=&ba;
  const std::array<VkDynamicState,2> states{VK_DYNAMIC_STATE_VIEWPORT,VK_DYNAMIC_STATE_SCISSOR};VkPipelineDynamicStateCreateInfo dy{VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO};dy.dynamicStateCount=2;dy.pDynamicStates=states.data();VkGraphicsPipelineCreateInfo ci{VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO};ci.stageCount=2;ci.pStages=stages.data();ci.pVertexInputState=&vi;ci.pInputAssemblyState=&ia;ci.pViewportState=&vp;ci.pRasterizationState=&rs;ci.pMultisampleState=&ms;ci.pColorBlendState=&bs;ci.pDynamicState=&dy;ci.layout=layout;ci.renderPass=pass;check(vkCreateGraphicsPipelines(d.device,VK_NULL_HANDLE,1,&ci,nullptr,&pipeline),"raster pipeline");vkDestroyShaderModule(d.device,vs,nullptr);vkDestroyShaderModule(d.device,fs,nullptr);
 }catch(...){if(vs)vkDestroyShaderModule(d.device,vs,nullptr);if(fs)vkDestroyShaderModule(d.device,fs,nullptr);release();throw;}}
 ~Raster(){release();}void release(){if(pipeline)vkDestroyPipeline(d.device,pipeline,nullptr);if(layout)vkDestroyPipelineLayout(d.device,layout,nullptr);for(auto fb:framebuffers)vkDestroyFramebuffer(d.device,fb,nullptr);if(pass)vkDestroyRenderPass(d.device,pass,nullptr);}
 void Record(unsigned mode){if(mode==0)return;const auto extent=target.Extent();const VkViewport viewport{0,0,float(extent.width),float(extent.height),0,1};const VkRect2D scissor{{0,0},extent};const std::array<unsigned,4> parameters{mode,extent.width,extent.height,0};for(auto fb:framebuffers){VkRenderPassBeginInfo bi{VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO};bi.renderPass=pass;bi.framebuffer=fb;bi.renderArea=scissor;vkCmdBeginRenderPass(d.commands,&bi,VK_SUBPASS_CONTENTS_INLINE);vkCmdSetViewport(d.commands,0,1,&viewport);vkCmdSetScissor(d.commands,0,1,&scissor);vkCmdBindPipeline(d.commands,VK_PIPELINE_BIND_POINT_GRAPHICS,pipeline);vkCmdPushConstants(d.commands,layout,VK_SHADER_STAGE_VERTEX_BIT|VK_SHADER_STAGE_FRAGMENT_BIT,0,16,parameters.data());vkCmdDraw(d.commands,3,1,0,0);vkCmdEndRenderPass(d.commands);}}
};

std::vector<std::byte> rasterChain(Device& d,Owner& owner,const Golden& g,AgcDriver::Graphics::RenderTarget& image,Raster& raster,unsigned mode,bool& initialized){using namespace AgcDriver::Graphics;
 ::Buffer tiled(d,g.tiled.size()),linear(d,g.linear.size());std::memcpy(tiled.data(),g.tiled.data(),g.tiled.size());std::memset(linear.data(),0xca,g.linear.size());owner.activate();ColorSampleTransfer samples(d.context,image,target(g));
 const ColorSampleImageAccess attachment{VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT,VK_ACCESS_COLOR_ATTACHMENT_READ_BIT|VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT};
 begin(d);record(d,owner,g,false,tiled,linear);samples.RecordUpload(d.commands,{linear.buffer,linear.offset,linear.bytes,VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,VK_ACCESS_SHADER_WRITE_BIT},initialized?ColorSampleImageAccess{VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,VK_ACCESS_SHADER_READ_BIT}:ColorSampleImageAccess{VK_IMAGE_LAYOUT_UNDEFINED,VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,0},attachment);raster.Record(mode);
 barrier(d,linear,VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT,VK_ACCESS_SHADER_READ_BIT,VK_PIPELINE_STAGE_TRANSFER_BIT,VK_ACCESS_TRANSFER_WRITE_BIT);vkCmdFillBuffer(d.commands,linear.buffer,linear.offset,linear.bytes,0xfefefefeu);
 samples.RecordReadback(d.commands,{linear.buffer,linear.offset,linear.bytes,VK_PIPELINE_STAGE_TRANSFER_BIT,VK_ACCESS_TRANSFER_WRITE_BIT},attachment,{VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,VK_ACCESS_SHADER_READ_BIT},VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT|VK_PIPELINE_STAGE_HOST_BIT,VK_ACCESS_SHADER_READ_BIT|VK_ACCESS_HOST_READ_BIT);
 record(d,owner,g,true,linear,tiled,VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,VK_ACCESS_SHADER_WRITE_BIT,VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT|VK_PIPELINE_STAGE_HOST_BIT,VK_ACCESS_SHADER_READ_BIT|VK_ACCESS_HOST_WRITE_BIT);submit(d);initialized=true;require(tiled.guardErrors()+linear.guardErrors()==0,"raster buffer guards");for(std::size_t i=0;i<g.offsets.size();++i)require(std::memcmp(tiled.data()+g.offsets[i],linear.data()+4*i,4)==0,"retile disagrees with actual ColorSampleTransfer readback");return{tiled.data(),tiled.data()+g.tiled.size()};
}
void negative(Device& d,Oracle& oracle,Mutation kind,unsigned identity){Owner owner(d,identity,true,"1");mutation=kind;auto g=golden(oracle,{33,65},8);for(unsigned mode=0;mode<2;++mode){const auto actual=compute(d,owner,g,mode);const auto expected=mode==0?g.linear:expectedRetile(g,0x5a,true);const auto corrupt=compareBytes(actual.data(),expected);require(corrupt>0,"wrong-specialization AMD-byte negative was not detected");std::printf("[pixel-negative] mutation=%s direction=%s AMD_corrupt_bytes=%llu detected=1\n",kind==Mutation::WrongXor?"wrong_sample_xor":"missing_sample_plane",mode?"retile":"detile",(unsigned long long)corrupt);}mutation=Mutation::None;}
void duplicate(Device& d,Owner& current,Oracle& oracle){auto g=golden(oracle,{17,19},8);::Buffer src(d,g.tiled.size()),dst(d,g.linear.size());begin(d);injectDuplicateZ=true;bool rejected=false;try{record(d,current,g,false,src,dst);}catch(const std::runtime_error& e){rejected=std::string(e.what())=="host dispatch contract rejected duplicate Z8";}injectDuplicateZ=false;fenceComplete=true;d.retained.clear();check(vkResetCommandBuffer(d.commands,0),"reset intentionally rejected dispatch");require(rejected&&duplicateRejected==1&&pendingPools.empty(),"duplicate-Z8 host dispatch negative");std::printf("[pixel-negative] duplicate_Z8=1 host_dispatch_contract_rejection=1 GPU_byte_inference=0 forwarded_to_GPU=0\n");}
void timestamps(Device& d,Owner& legacy,Owner& current,Oracle& oracle){
 std::uint32_t count=0;vkGetPhysicalDeviceQueueFamilyProperties(d.physical,&count,nullptr);std::vector<VkQueueFamilyProperties> families(count);vkGetPhysicalDeviceQueueFamilyProperties(d.physical,&count,families.data());unsigned bits=0;for(const auto& f:families)if(f.queueCount&&(f.queueFlags&(VK_QUEUE_GRAPHICS_BIT|VK_QUEUE_COMPUTE_BIT))==(VK_QUEUE_GRAPHICS_BIT|VK_QUEUE_COMPUTE_BIT)){bits=f.timestampValidBits;break;}
 if(!bits||!d.properties.limits.timestampComputeAndGraphics||!(d.properties.limits.timestampPeriod>0)){std::printf("[pixel-timestamp] supported=0 reason=queue_timestamp_limits\n");return;}VkQueryPool q{};VkQueryPoolCreateInfo qi{VK_STRUCTURE_TYPE_QUERY_POOL_CREATE_INFO};qi.queryType=VK_QUERY_TYPE_TIMESTAMP;qi.queryCount=2;if(vkCreateQueryPool(d.device,&qi,nullptr,&q)!=VK_SUCCESS){std::printf("[pixel-timestamp] supported=0 reason=query_pool_creation\n");return;}
 try{auto g=golden(oracle,{1920,1080},8);std::array<std::vector<double>,2> ns;for(unsigned repetition=0;repetition<5;++repetition)for(unsigned index=0;index<2;++index){auto result=compute(d,index?current:legacy,g,2,q);auto expected=expectedRetile(g,0xfe,false);require(result==expected,"timestamp case bytes");std::array<std::uint64_t,2> t{};check(vkGetQueryPoolResults(d.device,q,0,2,sizeof(t),t.data(),sizeof(t[0]),VK_QUERY_RESULT_64_BIT|VK_QUERY_RESULT_WAIT_BIT),"timestamp results");const auto mask=bits==64?UINT64_MAX:(std::uint64_t(1)<<bits)-1;ns[index].push_back(double((t[1]-t[0])&mask)*d.properties.limits.timestampPeriod);}for(auto& values:ns)std::sort(values.begin(),values.end());std::printf("[pixel-timestamp] supported=1 device=%s extent=1920x1080 samples=8 paired_repetitions=5 poison_chain_includes_fill_barriers=1 baseline_median_ns=%.0f current_median_ns=%.0f timestamp_period_ns=%.6f valid_bits=%u iPad_speed_claim=0\n",d.properties.deviceName,ns[0][2],ns[1][2],d.properties.limits.timestampPeriod,bits);vkDestroyQueryPool(d.device,q,nullptr);}catch(...){vkDestroyQueryPool(d.device,q,nullptr);throw;}
}
}
int main(){using namespace pixel_probe;try{Oracle oracle;Device d;d.tiler.reset();d.context.deviceProc=resolve;Owner legacy(d,1,false,"0"),current(d,2,true,"1");setenv("APS5_GPU_COLOR_SAMPLE_PIXEL_OWNED","changed-after-owner-capture",1);std::uint64_t coordinates=0,checked=0,padding=0,rasterChanged=0;unsigned computePairs=0,rasterPairs=0;
 for(unsigned samples:{2u,4u,8u})for(VkExtent2D extent: {VkExtent2D{1,1},{17,19},{31,63},{33,65},{257,129},{2049,19},{4097,19},{19,4097},{8193,19},{19,8193},{1920,1080}}){auto g=golden(oracle,extent,samples);coordinates+=g.offsets.size();for(unsigned mode=0;mode<3;++mode){auto a=compute(d,legacy,g,mode),b=compute(d,current,g,mode);const auto expected=mode==0?g.linear:expectedRetile(g,mode==1?0x5a:0xfe,mode==1);require(a==b&&a==expected,"paired compute disagreed with independent AMD bytes");checked+=g.offsets.size()*2;padding+=mode?(g.tiled.size()-g.linear.size())*2:0;++computePairs;}std::printf("[pixel-pair] extent=%ux%u samples=%u directions=2 poison_chain=1 padding_guards_offsets=1 pair_bytes_equal=1 AMD_bytes_equal=1\n",extent.width,extent.height,samples);}
 for(unsigned samples:{2u,4u,8u})for(VkExtent2D extent:{VkExtent2D{17,19},{33,65},{65,73},{4097,19},{19,4097}}){auto g=golden(oracle,extent,samples);AgcDriver::Graphics::RenderTarget image(d.context,target(g),false);Raster raster(d,image);bool initialized=false;std::uint64_t partial=0,discard=0;for(unsigned mode=0;mode<4;++mode){auto a=rasterChain(d,legacy,g,image,raster,mode,initialized),b=rasterChain(d,current,g,image,raster,mode,initialized);require(a==b,"paired ColorSampleTransfer raster bytes");std::uint64_t changes=0;for(auto offset:g.offsets)if(std::memcmp(a.data()+offset,g.tiled.data()+offset,4)){++changes;std::uint32_t value;std::memcpy(&value,a.data()+offset,4);require(value==0xff804020u,"independent RGBA8 raster golden");}for(std::size_t i=0;i<g.logical.size();++i)if(!g.logical[i])require(std::memcmp(a.data()+4*i,g.tiled.data()+4*i,4)==0,"raster padding seed changed");if(mode==0)require(changes==0&&a==g.tiled,"unchanged raster chain");if(mode==1){partial=changes;require(changes>0&&changes<g.offsets.size(),"partial coverage");}if(mode==2){discard=changes;require(changes>0&&changes<partial,"discard coverage");}if(mode==3)require(changes==g.offsets.size(),"full raster coverage");rasterChanged+=changes;checked+=g.offsets.size()*2;padding+=(g.tiled.size()-g.linear.size())*2;++rasterPairs;}std::printf("[pixel-raster] extent=%ux%u samples=%u groups=%u modes=4 partial_changed=%llu discard_changed=%llu pair_bytes_equal=1\n",extent.width,extent.height,samples,image.Groups(),(unsigned long long)partial,(unsigned long long)discard);}
 require(slots[1]==std::set<unsigned>({0,1,2,3,4,5})&&slots[2]==std::set<unsigned>({0,1,2,3,6,7}),"owner immutable cache/schema identity");duplicate(d,current,oracle);negative(d,oracle,Mutation::WrongXor,3);negative(d,oracle,Mutation::MissingPlane,4);Owner nonexact(d,5,false,"01");auto g=golden(oracle,{17,19},8);require(compute(d,nonexact,g,0)==g.linear,"nonexact gate unexpectedly enabled pixel module");timestamps(d,legacy,current,oracle);require(pendingPools.empty()&&poolsCreated==poolsDestroyed&&negativePrograms==4,"descriptor/program negative counts");std::printf("[pixel-owned] compute_pairs=%u raster_pairs=%u AMD_coordinates=%llu logical_words_checked=%llu padding_bytes_checked=%llu raster_changed_samples=%llu legacy_dispatches=%u pixel_dispatches=%u wrong_xor_direction_negatives=2 missing_plane_direction_negatives=2 duplicate_Z8_host_rejections=%u descriptor_fence_checks=%llu captured_gate_immutable=1 nonexact_gate_rejected=1 original_module_retained=1 owner_cache_identity=1 actual_ColorSampleTransfer=1 errors=0 status=PASS\n",computePairs,rasterPairs,(unsigned long long)coordinates,(unsigned long long)checked,(unsigned long long)padding,(unsigned long long)rasterChanged,legacyDispatches,pixelDispatches,duplicateRejected,(unsigned long long)descriptorFenceChecks);return 0;
 }catch(const std::exception& e){fenceComplete=true;std::fprintf(stderr,"[pixel-owned] FAIL %s\n",e.what());return 1;}}
