#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#define WINE_IOS 1
#ifndef __APPLE__
#define __APPLE__ 1
#endif
#define min(a,b) ((a) < (b) ? (a) : (b))
#define STATUS_SUCCESS UINT32_C(0)
#define STATUS_INVALID_PARAMETER UINT32_C(0xc000000d)
#define STATUS_ACCESS_DENIED UINT32_C(0xc0000022)
#define STATUS_THREAD_IS_TERMINATING UINT32_C(0xc000004b)
#define STATUS_PRIVILEGE_NOT_HELD UINT32_C(0xc0000061)
/* Actual Wine constants: ddk/wdm.h, winnt.h, winbase.h, winternl.h. */
enum {
    LOW_PRIORITY = 0, LOW_REALTIME_PRIORITY = 16, HIGH_PRIORITY = 31,
    PROCESS_PRIOCLASS_NORMAL = 2, PROCESS_PRIOCLASS_REALTIME = 4,
    THREAD_PRIORITY_IDLE = -15, THREAD_PRIORITY_TIME_CRITICAL = 15,
    THREAD_PRIORITY_LOWEST = -2, THREAD_PRIORITY_HIGHEST = 2,
    RUNNING = 0, TERMINATED = 1,
};
struct thread;
struct process { int priority, base_priority; struct thread *first; };
struct thread {
    struct process *process;
    int priority, base_priority, disable_boost, state, unix_tid;
    unsigned int ios_priority_status;
};
static unsigned int assertions, cases, apply_calls, apply_status;
static int enabled = 1, applied_effective;
static const char *case_name;
#define CHECK(condition) do { ++assertions; if (!(condition)) { \
    fprintf(stderr, "FAIL %s:%d: %s [%s]\n", __FILE__, __LINE__, #condition, case_name); exit(1); } } while (0)
static int ios_precedence_enabled(void) { return enabled; }
static struct thread *get_process_first_thread(struct process *process) { return process->first; }
int get_effective_thread_priority(struct thread *thread);
static void apply_thread_priority(struct thread *thread)
{
    ++apply_calls;
    applied_effective = get_effective_thread_priority(thread);
    thread->ios_priority_status = apply_status;
}
/* Generated by lexical extraction from the actual candidate thread.c. */
#include "generated_actual_priority_functions.h"

static struct process process;
static struct thread thread;
static void begin_case(const char *name)
{
    ++cases;
    case_name = name;
    enabled = 1; apply_calls = 0; apply_status = STATUS_SUCCESS; applied_effective = -1;
    memset(&process, 0, sizeof(process)); memset(&thread, 0, sizeof(thread));
    process.priority = PROCESS_PRIOCLASS_NORMAL; process.base_priority = 8;
    thread.process = &process; thread.priority = 8; thread.base_priority = 0;
    thread.state = RUNNING; thread.unix_tid = 99;
}
static void unchanged_metadata(void)
{
    CHECK(thread.priority == 8 && thread.base_priority == 0 && thread.disable_boost == 0);
}
int main(void)
{
    begin_case("actual-priority-failure-rolls-back-metadata");
    apply_status = STATUS_ACCESS_DENIED;
    CHECK(set_thread_priority(&thread, 10) == STATUS_ACCESS_DENIED);
    unchanged_metadata();
    CHECK(apply_calls == 1 && applied_effective == 10 && thread.ios_priority_status == STATUS_ACCESS_DENIED);

    begin_case("actual-priority-and-base-success-commit-and-input-validation");
    CHECK(set_thread_priority(&thread, 10) == STATUS_SUCCESS && thread.priority == 10);
    CHECK(apply_calls == 1 && applied_effective == 10);
    CHECK(set_thread_base_priority(&thread, THREAD_PRIORITY_HIGHEST) == STATUS_SUCCESS);
    CHECK(thread.priority == 10 && thread.base_priority == 2 && thread.disable_boost == 0 && apply_calls == 2);
    CHECK(set_thread_priority(&thread, 0) == STATUS_INVALID_PARAMETER && thread.priority == 10);
    CHECK(set_thread_priority(&thread, 32) == STATUS_INVALID_PARAMETER && thread.priority == 10);
    CHECK(set_thread_priority(&thread, 16) == STATUS_PRIVILEGE_NOT_HELD && thread.priority == 10);
    CHECK(apply_calls == 2);

    begin_case("actual-terminated-priority-base-and-boost-reject-before-apply");
    thread.state = TERMINATED;
    CHECK(set_thread_priority(&thread, 10) == STATUS_THREAD_IS_TERMINATING);
    unchanged_metadata();
    CHECK(set_thread_base_priority(&thread, 2) == STATUS_THREAD_IS_TERMINATING);
    unchanged_metadata();
    set_thread_disable_boost(&thread, 1);
    CHECK(thread.ios_priority_status == STATUS_THREAD_IS_TERMINATING);
    unchanged_metadata();
    CHECK(apply_calls == 0);

    begin_case("actual-prebootstrap-requests-queue-without-native-apply");
    thread.unix_tid = -1;
    apply_status = STATUS_ACCESS_DENIED;
    CHECK(set_thread_priority(&thread, 10) == STATUS_SUCCESS && thread.priority == 10);
    CHECK(set_thread_base_priority(&thread, 2) == STATUS_SUCCESS && thread.base_priority == 2 && thread.priority == 10);
    set_thread_disable_boost(&thread, 1);
    CHECK(thread.disable_boost == 1 && thread.ios_priority_status == STATUS_SUCCESS && apply_calls == 0);

    begin_case("actual-base-failure-rolls-back-both-base-and-priority");
    apply_status = STATUS_ACCESS_DENIED;
    CHECK(set_thread_base_priority(&thread, 2) == STATUS_ACCESS_DENIED);
    unchanged_metadata();
    CHECK(apply_calls == 1 && applied_effective == 10 && thread.ios_priority_status == STATUS_ACCESS_DENIED);

    begin_case("actual-boost-failure-restores-metadata-and-main-thread-boost");
    process.first = &thread;
    CHECK(get_effective_thread_priority(&thread) == 9);
    apply_status = STATUS_ACCESS_DENIED;
    set_thread_disable_boost(&thread, 1);
    unchanged_metadata();
    CHECK(apply_calls == 1 && applied_effective == 8 && thread.ios_priority_status == STATUS_ACCESS_DENIED);
    CHECK(get_effective_thread_priority(&thread) == 9);

    begin_case("actual-boost-success-commits");
    process.first = &thread;
    set_thread_disable_boost(&thread, 1);
    CHECK(thread.disable_boost == 1 && thread.priority == 8 && thread.base_priority == 0);
    CHECK(apply_calls == 1 && applied_effective == 8 && thread.ios_priority_status == STATUS_SUCCESS);
    CHECK(get_effective_thread_priority(&thread) == 8);

    begin_case("actual-gate-off-retains-baseline-terminated-metadata-behavior");
    enabled = 0; thread.state = TERMINATED;
    CHECK(set_thread_priority(&thread, 10) == STATUS_SUCCESS);
    CHECK(thread.priority == 10 && thread.base_priority == 0 && thread.disable_boost == 0 && apply_calls == 0);

    printf("{\"passed\":true,\"cases\":%u,\"assertions\":%u,\"actualCandidateFunctions\":true,\"realMachCalls\":false}\n", cases, assertions);
    return 0;
}
